version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:management
    hostname: ms-rabbit
    container_name: ms-rabbitmq
    ports:
      - '15672:15672'
  
  user-service-node:
    build: ./user-service
    container_name: ms-user-service
    ports:
      - "3000:3000"
    depends_on:
      - user-service-db
    volumes:
      - ./user-service:/usr/src/app
    command: npm run dev
  
  user-service-db:
    image: mongo
    container_name: ms-user-service-db
    volumes:
      - user-service-data:/data/db

  notification-service-node:
    build: ./notification-service
    container_name: ms-notification-service
    volumes:
      - ./notification-service:/usr/src/app
    environment:
      - MAILTRAP_HOST=${MAILTRAP_HOST}
      - MAILTRAP_PORT=${MAILTRAP_PORT}
      - MAILTRAP_USER=${MAILTRAP_USER}
      - MAILTRAP_PASS=${MAILTRAP_PASS}
    command: npm run dev

volumes:
  user-service-data: